Updated commit hook tests

diff --git a/bin/git-hook_pre-commit b/bin/git-hook_pre-commit
--- a/bin/git-hook_pre-commit
+++ b/bin/git-hook_pre-commit
@@ -13,70 +13,125 @@ set -u;
 # set -e;
 
 ## BEGIN Layout variables ==================================================
+NODE_EXE=$(which node);
 LINK_PATH=$(readlink -f -- "${0}");
-BIN_PATH=$(cd ${LINK_PATH%/*} && echo $PWD); # absolute path to this bin
-ROOT_DIR=$(cd "$(git rev-parse --show-toplevel)" && pwd );
-JSLINT_EXEC="${ROOT_DIR}/node_modules/jslint/bin/jslint.js";
-NODE_EXEC=$(which node);
-NODEUNIT_EXEC="${ROOT_DIR}/node_modules/nodeunit/bin/nodeunit";
-NODEUNIT_FILE="${ROOT_DIR}/test/t.js";
-MAKEDOC_EXEC="${ROOT_DIR}/bin/make_doc";
-TMP_FILE="/tmp/git-pre-commit.${$}tmp";
+BIN_PATH=$(cd "${LINK_PATH%/*}" && echo "${PWD}");
+GGG_DIR=$(cd "$(git rev-parse --show-toplevel)" && pwd );
+PKG_FILE=$(find "${GGG_DIR}" -type f -wholename "${GGG_DIR}/package.json" );
+PKG_DIR=$(dirname "${PKG_FILE}");
+MODS_DIR=$(find "${GGG_DIR}" -type d -wholename "${GGG_DIR}/node_modules" );
+WAPP_DIR=$(dirname "${MODS_DIR}");
+JSLINT_EXE="${MODS_DIR}/.bin/jslint";
+NU_EXE="${MODS_DIR}/.bin/nodeunit";
+NU_FILE="${WAPP_DIR}/test/t.js";
+MAKEDOC_EXE="${GGG_DIR}/bin/make_doc";
+LIST_FILE="/tmp/git-pre-commit.${$}.list.tmp";
+TMP_FILE="/tmp/git-pre-commit.${$}.tmp";
+CHECK_STR="";
 ## END Layout variables ====================================================
 
+## BEGIN Debug
+# echo "
+# NODE_EXE     : ${NODE_EXE}
+# LINK_PATH    : ${LINK_PATH}
+# BIN_PATH     : ${BIN_PATH}
+# GGG_DIR      : ${GGG_DIR}
+# PKG_FILE     : ${PKG_FILE}
+# PKG_DIR      : ${PKG_DIR}
+# MODS_DIR     : ${MODS_DIR}
+# WAPP_DIR     : ${WAPP_DIR}
+# JSLINT_EXE   : ${JSLINT_EXE}
+# NU_EXE       : ${NU_EXE}
+# NU_FILE      : ${NU_FILE}
+# MAKEDOC_EXE  : ${MAKEDOC_EXE}
+# LIST_FILE    : ${LIST_FILE}
+# TMP_FILE     : ${TMP_FILE}
+# CHECK_STR    : ${CHECK_STR}
+# ";
+# exit 0;
+## END Debug
+
 ## BEGIN Lint JavaScript files =============================================
-if [ ! -x "${JSLINT_EXEC}" ] || [ ! -x "${NODEUNIT_EXEC}" ]; then
-  echo "Development libraries not found."
+if [ ! -x "${JSLINT_EXE}" ]; then
+  echo "JSLint executable not found."
   echo "Please execute the following command: "
-  echo "  cd ${ROOT_DIR}; npm install ";
+  echo "  cd ${WAPP_DIR}; npm install ";
   exit 1;
 fi
 
-echo;
-echo "JSLint test of updated or new *.js files ...";
-echo "  We ignore vendor libraries in .../vendor/...";
+cd "${GGG_DIR}";
+pwd;
+
 git status \
   | grep '.js$' \
   | grep -v '/vendor/' \
   | grep -v 'pcss._ex004_.js' \
   | grep '^\s\+\(modified\|new file\)' \
-  | cut -d ":" -f 2- \
-  | while read LINE; do
-      echo -en "  Check ${LINE}: ... "
-      CHECK_STR=$(${JSLINT_EXEC} ${LINE});
-      CHECK_CODE=$?;
-      echo "${CHECK_CODE}"
-      if [ "${CHECK_CODE}" -gt 0 ]; then
-        echo "${LINE} JSLint check FAILED";
-        echo "${CHECK_STR}";
-      else
-        echo "pass";
-      fi;
-    done \
-  | tee "${TMP_FILE}";
+  | cut -d ":" -f 2- > "${LIST_FILE}"
 
-echo "JSLint test complete";
-if grep -s 'FAIL' "${TMP_FILE}"; then
-  echo "FAIL: JSLint checks did not pass.";
-  echo "  Please use jslint to test the problem files and ";
-  echo "  commit again once they pass the check.";
+## BEGIN Debug
+# echo ">>>>${LIST_FILE}<<<<";
+# echo ">>>>LIST_FILE:";
+# cat "${LIST_FILE}";
+# echo "<<<<";
+# exit 1;
+## END Debug
+
+echo;
+echo "Tests of updated or new *.js files ...";
+cat "${LIST_FILE}" | while read FILE_NAME; do
+  echo "====> ${FILE_NAME}";
+  CHECK_STR=$(${JSLINT_EXE} "${FILE_NAME}");
+  CHECK_CODE=$?;
+  if [ "${CHECK_CODE}" -gt 0 ]; then
+    echo "  JSLint check FAILED";
+    echo "  ${CHECK_STR}";
+  fi;
+  CHECK_STR=$(grep -nP '\t' "${FILE_NAME}");
+  if [ ! -z "${CHECK_STR}" ]; then
+    echo "  Tab check FAILED";
+    echo "  ${CHECK_STR}";
+    echo;
+  fi
+  CHECK_STR=$(grep -nP '\s+$' ${FILE_NAME});
+  if [ ! -z "${CHECK_STR}" ]; then
+    echo "  Trailing space check FAILED";
+    echo "  ${CHECK_STR}";
+    echo;
+  fi
+  CHECK_STR=$(grep '^\s*.use strict.;$' ${FILE_NAME});
+  if [ -z "${CHECK_STR}" ]; then
+    echo "  Strict use check FAILED";
+    echo "  Please add 'use strict'; at the top of your module function.";
+    echo;
+  fi
+  echo "<====";
+  echo;
+done | tee "${TMP_FILE}";
+
+echo "Tests complete";
+if grep -qs 'FAIL' "${TMP_FILE}"; then
+  echo "Checks did not pass.";
+  echo "  Please fix the problem files and commit again.";
   rm "${TMP_FILE}";
   exit 1;
 fi
 
 rm "${TMP_FILE}";
+rm "${LIST_FILE}";
+
 echo;
 ## END Lint JavaScript files ===============================================
 
-## BEGIN Progress changed documents ========================================
+## BEGIN Process changed documents ========================================
 ## TODO
-##  if [ ! -x "${MAKEDOC_EXEC}" ]; then
+##  if [ ! -x "${MAKEDOC_EXE}" ]; then
 ##    echo "bin/make_doc not found.  This file should exist.";
 ##    echo "Please check your installation.";
 ##    exit 1;
 ##  fi
 ##  echo "Updating HTML documents from MarkDown";
-##  "${MAKEDOC_EXEC}";
+##  "${MAKEDOC_EXE}";
 ##  RET_VAL=$?;
 ##  if [ "${RET_VAL}" -eq "0" ]; then
 ##    echo "Document file failure".
@@ -84,29 +139,29 @@ echo;
 ##    exit "${RET_VAL}";
 ##  fi
 ##
-## END Progress changed documents ==========================================
+## END Process changed documents ==========================================
 
 ## BEGIN Run regression tests ==============================================
-if [ ! -x "${NODE_EXEC}" ]; then
+if [ ! -x "${NODE_EXE}" ]; then
   echo "Node not found.  Please install nodejs and ensure it is "
   echo " found in your PATH environment variable."
   exit 1;
 fi
 
-if [ ! -x "${NODEUNIT_EXEC}" ]; then
+if [ ! -x "${NU_EXE}" ]; then
   echo "Nodeunit not found.  Please run "
-  echo "cd ${ROOT_DIR}; npm install"
+  echo "cd ${WAPP_DIR}; npm install"
   echo
 fi
 
-if [ ! -r "${NODEUNIT_FILE}" ]; then
-  echo "Nodeunit file ${NODEUNIT_FILE} not found."
+if [ ! -r "${NU_FILE}" ]; then
+  echo "Nodeunit file ${NU_FILE} not found."
   echo "Please ensure it exists."
   echo
   exit 1;
 fi
 
 echo "Running regression tests";
-"${NODEUNIT_EXEC}" "${NODEUNIT_FILE}"
+"${NU_EXE}" "${NU_FILE}"
 exit $?;
 ## END Run regression tests ================================================
